version: "3"
services:
    application:
        build: .
        restart: always
        volumes: ["./certs:/data/certs"]
        command: /data/launch --root https://beta.qbin.io --force-root --http :80 --tcp :90 --https :443 --hsts
        ports:
        - "80:80"
        - "90:90"
        - "443:443"
        links: ["database:database"]
        environment:
        - "DATABASE=root:qbin-K4Y76GQBB1DqTs6VH3aV@tcp(database)/qbin"
    database:
        image: mariadb
        restart: always
        volumes: ["./storage:/var/lib/mysql"]
        environment:
            MYSQL_DATABASE: qbin
            # Make sure you generate a new password:
            # sed -i 's|qbin-K4Y76GQBB1DqTs6VH3aV|qbin-'$(cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 20)'|g' docker-compose.yml
            MYSQL_ROOT_PASSWORD: qbin-K4Y76GQBB1DqTs6VH3aV
