version: "3"
services:
    application:
        build: .
        networks: [main]
        restart: always
        ports:
        - "80:80"
        - "90:90"
        - "443:443"
        environment:
        - "LISTEN_HTTPS=:443"
        - "ROOT=https://beta.qbin.io/"
        - "DATABASE=root:qbin-K4Y76GQBB1DqTs6VH3aV@database/qbin"
    database:
        image: mariadb
        networks: [main]
        restart: always
        volumes: ["./storage:/var/lib/mysql"]
        environment:
            # Make sure you generate a new password:
            # sed -i 's|K4Y76GQBB1DqTs6VH3aV|'$(cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 20)'|g' docker-compose.yml
            MYSQL_ROOT_PASSWORD: qbin-K4Y76GQBB1DqTs6VH3aV
networks:
    main:
        driver: bridge
